### ISSUE TITLE
saving/loading the model raises issues

### ISSUE THREAD

**Issue by pasq-cat** [aurelio-amerio/ConcreteDropout-TF2#2]
Hi, i was trying to save the a model that has few concretedropouts layers  but i am facing an issue

first,when i save the model i need to set the old h5 format 
`concrete_dropout_BNN.save("concrete_dropout_BNN",save_format='h5' ) `
otherwise i get an error

but, and that's the real problem, when i try to load it with

`   tf.keras.models.load_model("concrete_dropout_BNN")`
 i get 
`ValueError: Unknown layer: ConcreteDenseDropout. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details.`

how do i solve this issue? thanks

**Comment by aurelio-amerio** [comment]
Hello, which error are you getting when you try to save the model in the "not h5" format (ie folder format)? You should be able to save and load your model in all the supported tf formats. If it doesn't work, there might be a bug either in your code or this library. 

Concearning the other problem, if you are loading a model in h5 format, you need to pass a "custom_object" dictionary, which contains elements of the type "ConcreteDenseDropout":ConcreteDenseDropout

Please read the guide which was printed together with the error for more info on that, as this is not a bug, rather just how loading custom layers from an h5 file works.
